import audi1 from '../assets/AUDI/1.png'
import audi2 from '../assets/AUDI/2.png'
import audi3 from '../assets/AUDI/3.png'
import audi4 from '../assets/AUDI/4.png'
import audi5 from '../assets/AUDI/5.png'
import bmw1 from '../assets/BMW/1.jpeg'
import bmw2 from '../assets/BMW/2.jpg'
import bmw3 from '../assets/BMW/3.png'
import bmw4 from '../assets/BMW/4.png'
import bmw5 from '../assets/BMW/5.png'
import dodge1 from '../assets/DODGE/1.png'
import dodge2 from '../assets/DODGE/2.png'
import dodge3 from '../assets/DODGE/3.png'
import dodge4 from '../assets/DODGE/4.png'
import mercedes1 from '../assets/MERCEDES/1.png'
import mercedes2 from '../assets/MERCEDES/2.png'
import mercedes3 from '../assets/MERCEDES/3.jpg'
import mercedes4 from '../assets/MERCEDES/4.png'
import mercedes5 from '../assets/MERCEDES/5.png'
import rover1 from '../assets/RANGE-ROVER/1.jpg'
import rover2 from '../assets/RANGE-ROVER/2.png'
import rover3 from '../assets/RANGE-ROVER/3.png'
import rover4 from '../assets/RANGE-ROVER/4.png'
import rover5 from '../assets/RANGE-ROVER/5.png'
import tesla1 from '../assets/TESLA/1.png'
import tesla2 from '../assets/TESLA/2.png'
import tesla3 from '../assets/TESLA/3.jpeg'
import tesla4 from '../assets/TESLA/4.png'
import tesla5 from '../assets/TESLA/5.png'
import toyota1 from '../assets/TOYOTA/1.png'
import toyota2 from '../assets/TOYOTA/2.png'
import toyota3 from '../assets/TOYOTA/3.png'
import toyota4 from '../assets/TOYOTA/4.png'
import toyota5 from '../assets/TOYOTA/5.png'
const data = [
  {
    id: 1,
    img: audi1,
    title: "Audi A5 2016",
    reviews: "(123 просмотров)",
    price: "10",
    company: "Audi",
    color: "grey",
    category: "Купе",
  },
  {
    id: 2,
    img: bmw1,
    title: "BMW M5",
    reviews: "(123 просмотров)",
    price: "25",
    company: "BMW",
    color: "white",
    category: "Купе",
  },
  {
    id: 3,
    img: dodge1,
    title: "Dodge Challenger",
    reviews: "(123 просмотров)",
    price: "40",
    company: "Dodge",
    color: "white",
    category: "Спорткар",
  },
  {
    id: 4,
    img: mercedes1,
    title: "Mercedes 1",
    reviews: "(123 просмотров)",
    price: "25",
    company: "Mercedes",
    color: "grey",
    category: "Кабриолет",
  },
  {
    id: 5,
    img: rover1,
    title: "Range-Rover 1",
    reviews: "(123 просмотров)",
    price: "55",
    company: "Range-Rover",
    color: "white",
    category: "Внедорожник",
  },
  {
    id: 6,
    img: tesla1,
    title: "Tesla Model 3",
    reviews: "(123 просмотров)",
    price: "30",
    company: "Tesla",
    color: "white",
    category: "Электрокар",
  },
  {
    id: 7,
    img: toyota1,
    title: "Toyota  1",
    reviews: "(123 просмотров)",
    price: "20",
    company: "Toyota",
    color: "white",
    category: "Седан",
  },
  {
    id: 8,
    img: audi2,
    title: "Audi Q3 2018",
    reviews: "(123 просмотров)",
    price: "50",
    company: "Audi",
    color: "black",
    category: "Купе",
  },
  {
    id: 9,
    img: bmw2,
    title: "BMW 2",
    reviews: "(123 просмотров)",
    price: "30",
    company: "BMW",
    color: "white",
    category: "Седан",
  },
  {
    id: 10,
    img: dodge2,
    title: "Dodge 2",
    reviews: "(123 просмотров)",
    price: "25",
    company: "Dodge",
    color: "black",
    category: "Седан",
  },
  {
    id: 11,
    img: mercedes2,
    title: "Mercedes 2",
    reviews: "(123 просмотров)",
    price: "30",
    company: "Mercedes",
    color: "grey",
    category: "Седан",
  },
  {
    id: 12,
    img: rover2,
    title: "Range Rover 2",
    reviews: "(123 просмотров)",
    price: "60",
    company: "Range-Rover",
    color: "blue",
    category: "Внедорожник",
  },
  {
    id: 13,
    img: tesla2,
    title: "Tesla 2",
    reviews: "(123 просмотров)",
    price: "45",
    company: "Tesla",
    color: "grey",
    category: "Электрокар",
  },
  {
    id: 14,
    img: toyota2,
    title: "Toyota 2",
    reviews: "(123 просмотров)",
    price: "20",
    company: "Toyota",
    color: "grey",
    category: "Седан",
  },
  {
    id: 15,
    img: audi3,
    title: "Audi 3",
    reviews: "(123 просмотров)",
    price: "25",
    company: "Audi",
    color: "red",
    category: "Спорткар",
  },
  {
    id: 16,
    img: bmw3,
    title: "BMW 4 Series",
    reviews: "(123 просмотров)",
    price: "25",
    company: "BMW",
    color: "red",
    category: "Купе",
  },
  {
    id: 17,
    img: dodge3,
    title: "Dodge 3",
    reviews: "(123 просмотров)",
    price: "35",
    company: "Dodge",
    color: "red",
    category: "Седан",
  },
  {
    id: 18,
    img: mercedes3,
    title: "Mercedes 3",
    reviews: "(123 просмотров)",
    price: "50",
    company: "Mercedes",
    color: "grey",
    category: "Седан",
  },
  {
    id: 19,
    img: rover3,
    title: "Range-Rover 3",
    reviews: "(123 просмотров)",
    price: "45",
    company: "Range-Rover",
    color: "red",
    category: "Внедорожник",
  },
  {
    id: 20,
    img: tesla3,
    title: "Tesla Cybertruck 2023",
    reviews: "(123 просмотров)",
    price: "60",
    company: "Tesla",
    color: "grey",
    category: "Электрокар",
  },
  {
    id: 21,
    img: toyota3,
    title: "Toyota 3",
    reviews: "(123 просмотров)",
    price: "35",
    company: "Toyota",
    color: "black",
    category: "Седан",
  },
  {
    id: 22,
    img: audi4,
    title: "Audi 4",
    reviews: "(123 просмотров)",
    price: "40",
    company: "Audi",
    color: "white",
    category: "Внедорожник",
  },
  {
    id: 23,
    img: bmw4,
    title: "BMW i8",
    reviews: "(123 просмотров)",
    price: "60",
    company: "BMW",
    color: "white",
    category: "Спорткар",
  },
  {
    id: 24,
    img: dodge4,
    title: "Dodge 4",
    reviews: "(123 просмотров)",
    price: "45",
    company: "Dodge",
    color: "white",
    category: "Седан",
  },
  {
    id: 25,
    img: mercedes4,
    title: "Mercedes 4",
    reviews: "(123 просмотров)",
    price: "40",
    company: "Mercedes",
    color: "white",
    category: "Седан",
  },
  {
    id: 26,
    img: rover4,
    title: "Range-Rover 4",
    reviews: "(123 просмотров)",
    price: "50",
    company: "Range-Rover",
    color: "red",
    category: "Внедорожник",
  },
  {
    id: 27,
    img: tesla4,
    title: "Tesla 4",
    reviews: "(123 просмотров)",
    price: "40",
    company: "Tesla",
    color: "red",
    category: "Электрокар",
  },
  {
    id: 28,
    img: toyota4,
    title: "Toyota 4",
    reviews: "(123 просмотров)",
    price: "35",
    company: "Toyota",
    color: "white",
    category: "Седан",
  },
  {
    id: 29,
    img: audi5,
    title: "Audi 5",
    reviews: "(123 просмотров)",
    price: "55",
    company: "Audi",
    color: "white",
    category: "Внедорожник",
  },
  {
    id: 30,
    img: bmw5,
    title: "BMW M2 2018",
    reviews: "(123 просмотров)",
    price: "20",
    company: "BMW",
    color: "blue",
    category: "Купе",
  },
  {
    id: 31,
    img: mercedes5,
    title: "Mercedes 5",
    reviews: "(123 просмотров)",
    price: "40",
    company: "Mercedes",
    color: "white",
    category: "Седан",
  },
  {
    id: 32,
    img: rover5,
    title: "Range-Rover 5",
    reviews: "(123 просмотров)",
    price: "45",
    company: "Range-Rover",
    color: "grey",
    category: "Внедорожник",
  },
  {
    id: 33,
    img: tesla5,
    title: "Tesla 5",
    reviews: "(123 просмотров)",
    price: "40",
    company: "Tesla",
    color: "black",
    category: "Электрокар",
  },
  {
    id: 34,
    img: toyota5,
    title: "Toyota 5",
    reviews: "(123 просмотров)",
    price: "45",
    company: "Toyota",
    color: "grey",
    category: "Седан",
  },
];

export default data;
